-- locale.lua (Sistema de Localização)

local addonName = ...
local L = {}

-- Detectar idioma do cliente
local locale = GetLocale()

-- ========================================
-- PORTUGUÊS BRASILEIRO (ptBR)
-- ========================================
if locale == "ptBR" then
    -- Titulos de Mensagens
    L["WHISPER_TITLE"] = "%s (Sussurro):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (Guilda):"
    L["PARTY_TITLE"] = "%s (Grupo):"
    L["RAID_TITLE"] = "%s (Raide):"
    
    -- Menu de Opcoes
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "Configuracoes do WhisperToast.\\n|cffff8800Comandos:|r /wt move | /wt test"
    
    -- Secoes
    L["SECTION_NOTIFICATIONS"] = "Tipos de Notificacoes"
    L["SECTION_APPEARANCE"] = "Aparencia"
    L["SECTION_COLORS"] = "Cores"
    L["SECTION_COLORS_CHAT"] = "Cores por Tipo de Chat"
    L["SECTION_SOUND"] = "Som"
    L["SECTION_SOUND_INDIVIDUAL"] = "Sons Individuais por Tipo"
    L["SECTION_BEHAVIOR"] = "Comportamento"
    L["SECTION_POSITION"] = "Posicionamento"
    
    -- Tipos de Notificacoes
    L["WHISPER_TOGGLE"] = "Sussurros e BNet"
    L["WHISPER_DESC"] = "Mostrar notificacoes de sussurros"
    L["GUILD_TOGGLE"] = "Guilda"
    L["GUILD_DESC"] = "Mostrar notificacoes da guilda"
    L["PARTY_TOGGLE"] = "Grupo"
    L["PARTY_DESC"] = "Mostrar notificacoes de grupo (party)"
    L["RAID_TOGGLE"] = "Raide"
    L["RAID_DESC"] = "Mostrar notificacoes de raide"
    
    -- Aparencia
    L["WIDTH"] = "Largura"
    L["HEIGHT"] = "Altura"
    L["MAX_CHARS"] = "Maximo de Caracteres"
    L["MAX_CHARS_DESC"] = "Numero maximo de caracteres exibidos"
    
    -- Cores
    L["BG_COLOR"] = "Cor de Fundo"
    L["BG_COLOR_DESC"] = "Cor do fundo da notificacao (parte de tras da caixa)"
    L["BORDER_COLOR"] = "Cor da Borda"
    L["BORDER_COLOR_DESC"] = "Cor da borda e efeitos brilhantes ao redor da notificacao"
    L["TITLE_COLOR"] = "Cor do Titulo (Padrao)"
    L["TITLE_COLOR_DESC"] = "Cor padrao do titulo quando nao usa cores por tipo de chat"
    L["TEXT_COLOR"] = "Cor do Texto"
    L["TEXT_COLOR_DESC"] = "Cor do texto da mensagem (corpo da notificacao)"
    L["WHISPER_COLOR"] = "Cor do Sussurro"
    L["WHISPER_COLOR_DESC"] = "Cor do nome do remetente em sussurros (mensagens privadas WoW)"
    L["BNET_COLOR"] = "Cor do Battle.net"
    L["BNET_COLOR_DESC"] = "Cor do nome do remetente em mensagens do Battle.net"
    L["GUILD_COLOR"] = "Cor da Guilda"
    L["GUILD_COLOR_DESC"] = "Cor do nome do remetente em mensagens da guilda"
    L["PARTY_COLOR"] = "Cor do Grupo"
    L["PARTY_COLOR_DESC"] = "Cor do nome do remetente em mensagens de grupo (party)"
    L["RAID_COLOR"] = "Cor da Raide"
    L["RAID_COLOR_DESC"] = "Cor do nome do remetente em mensagens de raide"
    
    -- Som
    L["SOUND_ENABLE"] = "Ativar Sons (Global)"
    L["SOUND_ENABLE_DESC"] = "Ativa/desativa TODOS os sons do addon"
    L["SOUND_VOLUME"] = "Canal de Volume"
    L["SOUND_VOLUME_DESC"] = "Canal de audio usado para reproduzir os sons"
    L["SOUND_VOLUME_MASTER"] = "Master"
    L["SOUND_VOLUME_SOUND"] = "Efeitos Sonoros"
    L["SOUND_VOLUME_MUSIC"] = "Musica"
    L["SOUND_VOLUME_AMBIENCE"] = "Ambiente"
    L["SOUND_VOLUME_DIALOG"] = "Dialogo"
    L["SOUND_WHISPER"] = "Som de Sussurro"
    L["SOUND_WHISPER_TOGGLE"] = "Som de Sussurro"
    L["SOUND_WHISPER_TOGGLE_DESC"] = "Ativar som para sussurros"
    L["SOUND_WHISPER_SELECT"] = "Escolher Som (Sussurro)"
    L["SOUND_WHISPER_SELECT_DESC"] = "Clique para ouvir previa"
    L["SOUND_GUILD"] = "Som de Guilda"
    L["SOUND_GUILD_TOGGLE"] = "Som de Guilda"
    L["SOUND_GUILD_TOGGLE_DESC"] = "Ativar som para mensagens da guilda"
    L["SOUND_GUILD_SELECT"] = "Escolher Som (Guilda)"
    L["SOUND_GUILD_SELECT_DESC"] = "Clique para ouvir previa"
    L["SOUND_PARTY"] = "Som de Grupo"
    L["SOUND_PARTY_TOGGLE"] = "Som de Grupo"
    L["SOUND_PARTY_TOGGLE_DESC"] = "Ativar som para mensagens de grupo"
    L["SOUND_PARTY_SELECT"] = "Escolher Som (Grupo)"
    L["SOUND_PARTY_SELECT_DESC"] = "Clique para ouvir previa"
    L["SOUND_RAID"] = "Som de Raide"
    L["SOUND_RAID_TOGGLE"] = "Som de Raide"
    L["SOUND_RAID_TOGGLE_DESC"] = "Ativar som para mensagens de raide"
    L["SOUND_RAID_SELECT"] = "Escolher Som (Raide)"
    L["SOUND_RAID_SELECT_DESC"] = "Clique para ouvir previa"
    -- Nomes de Sons
    L["SOUND_NAME_11504"] = "Sussurro (Padrao)"
    L["SOUND_NAME_8960"] = "Guilda (Padrao)"
    L["SOUND_NAME_11487"] = "Grupo (Padrao)"
    L["SOUND_NAME_567"] = "Mapa Aberto"
    L["SOUND_NAME_850"] = "Sino"
    L["SOUND_NAME_1190"] = "Caixa Coletada"
    L["SOUND_NAME_5274"] = "Gong"
    L["SOUND_NAME_8959"] = "Tell"
    L["SOUND_NAME_12867"] = "Porta Abrindo"
    L["SOUND_NAME_29495"] = "Fanfarra"
    L["SOUND_NAME_3081"] = "Dinheiro Coletado"
    L["SOUND_NAME_5841"] = "Level Up"
    L["SOUND_NAME_12889"] = "Raid Warning"
    L["SOUND_NAME_8745"] = "Conquista"
    L["SOUND_NAME_11466"] = "Quest Completa"
    L["SOUND_NAME_6595"] = "Exploracao"
    L["SOUND_NAME_5174"] = "PvP Flag"
    L["SOUND_NAME_878"] = "Interface Click"
    L["SOUND_NAME_569"] = "Menu Pop"
    L["SOUND_NAME_1080"] = "Item Raro"
    L["SOUND_NAME_8835"] = "Interface Humano"
    L["SOUND_NAME_11742"] = "Loot Epico"
    L["SOUND_NAME_8477"] = "Ready Check"
    L["SOUND_NAME_3400"] = "Alarme Torre"
    L["SOUND_NAME_21388"] = "Apito"
    
    -- Comportamento
    L["DISPLAY_TIME"] = "Tempo de Exibicao"
    L["DISPLAY_TIME_DESC"] = "Quantos segundos a notificacao fica visivel na tela"
    L["SHOW_PORTRAIT"] = "Mostrar Retrato"
    L["SHOW_PORTRAIT_DESC"] = "Exibir retrato do personagem (apenas para jogadores em grupo/proximos)"
    
    -- Botoes
    L["BTN_MOVE"] = "Mover Ancora"
    L["BTN_MOVE_DESC"] = "Mostra uma ancora verde animada que voce pode arrastar para reposicionar as notificacoes"
    L["BTN_TEST"] = "Mostrar Teste"
    L["BTN_TEST_DESC"] = "Exibe uma notificacao de teste para voce ver como esta configurado"
    L["BTN_RESET_POS"] = "Resetar Posicao"
    L["BTN_RESET_POS_DESC"] = "Volta a ancora para o centro da tela (posicao padrao)"
    L["BTN_RESET_ALL"] = "Resetar Tudo"
    L["BTN_RESET_ALL_DESC"] = "Restaura TODAS as configuracoes para os valores padrao e recarrega a interface"
    L["BTN_RESET_CONFIRM"] = "Resetar TODAS as configuracoes?"
    
    -- Mensagens
    L["ANCHOR_TEXT"] = "|cff00ff00Arraste para Mover|r\\n|cffaaaaaa/wt move para esconder|r"
    L["POS_SAVED"] = "|cff00ff00Posicao salva:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "Posicao resetada"
    L["SLASH_HELP"] = "Use as opcoes do addon em: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "Esta e uma mensagem de teste para voce ver como ficou a personalizacao!"
elseif locale == "enUS" or locale == "enGB" then
    L["WHISPER_TITLE"] = "%s (Whisper):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (Guild):"
    L["PARTY_TITLE"] = "%s (Party):"
    L["RAID_TITLE"] = "%s (Raid):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "WhisperToast Settings.\n|cffff8800Commands:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "Notification Types"
    L["SECTION_APPEARANCE"] = "Appearance"
    L["SECTION_COLORS"] = "Colors"
    L["SECTION_COLORS_CHAT"] = "Colors by Chat Type"
    L["SECTION_SOUND"] = "Sound"
    L["SECTION_SOUND_INDIVIDUAL"] = "Individual Sounds by Type"
    L["SECTION_BEHAVIOR"] = "Behavior"
    L["SECTION_POSITION"] = "Positioning"
    
    L["WHISPER_TOGGLE"] = "Whispers & BNet"
    L["WHISPER_DESC"] = "Show whisper notifications"
    L["GUILD_TOGGLE"] = "Guild"
    L["GUILD_DESC"] = "Show guild notifications"
    L["PARTY_TOGGLE"] = "Party"
    L["PARTY_DESC"] = "Show party notifications"
    L["RAID_TOGGLE"] = "Raid"
    L["RAID_DESC"] = "Show raid notifications"
    
    L["WIDTH"] = "Width"
    L["HEIGHT"] = "Height"
    L["MAX_CHARS"] = "Max Characters"
    L["MAX_CHARS_DESC"] = "Maximum characters displayed"
    
    L["BG_COLOR"] = "Background Color"
    L["BG_COLOR_DESC"] = "Notification background color (back of the box)"
    L["BORDER_COLOR"] = "Border Color"
    L["BORDER_COLOR_DESC"] = "Border and glow effects color around notification"
    L["TITLE_COLOR"] = "Title Color (Default)"
    L["TITLE_COLOR_DESC"] = "Default title color when not using chat type colors"
    L["TEXT_COLOR"] = "Text Color"
    L["TEXT_COLOR_DESC"] = "Message text color (notification body)"
    L["WHISPER_COLOR"] = "Whisper Color"
    L["WHISPER_COLOR_DESC"] = "Sender name color in whispers (WoW private messages)"
    L["BNET_COLOR"] = "Battle.net Color"
    L["BNET_COLOR_DESC"] = "Sender name color in Battle.net messages"
    L["GUILD_COLOR"] = "Guild Color"
    L["GUILD_COLOR_DESC"] = "Sender name color in guild messages"
    L["PARTY_COLOR"] = "Party Color"
    L["PARTY_COLOR_DESC"] = "Sender name color in party messages"
    L["RAID_COLOR"] = "Raid Color"
    L["RAID_COLOR_DESC"] = "Sender name color in raid messages"
    
    L["SOUND_ENABLE"] = "Enable Sounds (Global)"
    L["SOUND_ENABLE_DESC"] = "Enable/disable ALL addon sounds"
    L["SOUND_VOLUME"] = "Volume Channel"
    L["SOUND_VOLUME_DESC"] = "Audio channel used to play sounds"
    L["SOUND_VOLUME_MASTER"] = "Master"
    L["SOUND_VOLUME_SOUND"] = "Sound Effects"
    L["SOUND_VOLUME_MUSIC"] = "Music"
    L["SOUND_VOLUME_AMBIENCE"] = "Ambience"
    L["SOUND_VOLUME_DIALOG"] = "Dialog"
    L["SOUND_WHISPER_TOGGLE"] = "Whisper Sound"
    L["SOUND_WHISPER_TOGGLE_DESC"] = "Enable sound for whispers"
    L["SOUND_WHISPER_SELECT"] = "Choose Sound (Whisper)"
    L["SOUND_WHISPER_SELECT_DESC"] = "Click to preview"
    L["SOUND_GUILD_TOGGLE"] = "Guild Sound"
    L["SOUND_GUILD_TOGGLE_DESC"] = "Enable sound for guild messages"
    L["SOUND_GUILD_SELECT"] = "Choose Sound (Guild)"
    L["SOUND_GUILD_SELECT_DESC"] = "Click to preview"
    L["SOUND_PARTY_TOGGLE"] = "Party Sound"
    L["SOUND_PARTY_TOGGLE_DESC"] = "Enable sound for party messages"
    L["SOUND_PARTY_SELECT"] = "Choose Sound (Party)"
    L["SOUND_PARTY_SELECT_DESC"] = "Click to preview"
    L["SOUND_RAID_TOGGLE"] = "Raid Sound"
    L["SOUND_RAID_TOGGLE_DESC"] = "Enable sound for raid messages"
    L["SOUND_RAID_SELECT"] = "Choose Sound (Raid)"
    L["SOUND_RAID_SELECT_DESC"] = "Click to preview"
    -- Sound Names
    L["SOUND_NAME_11504"] = "Whisper (Default)"
    L["SOUND_NAME_8960"] = "Guild (Default)"
    L["SOUND_NAME_11487"] = "Party (Default)"
    L["SOUND_NAME_567"] = "Map Open"
    L["SOUND_NAME_850"] = "Bell"
    L["SOUND_NAME_1190"] = "Chest Looted"
    L["SOUND_NAME_5274"] = "Gong"
    L["SOUND_NAME_8959"] = "Tell"
    L["SOUND_NAME_12867"] = "Door Opening"
    L["SOUND_NAME_29495"] = "Fanfare"
    L["SOUND_NAME_3081"] = "Money Looted"
    L["SOUND_NAME_5841"] = "Level Up"
    L["SOUND_NAME_12889"] = "Raid Warning"
    L["SOUND_NAME_8745"] = "Achievement"
    L["SOUND_NAME_11466"] = "Quest Complete"
    L["SOUND_NAME_6595"] = "Exploration"
    L["SOUND_NAME_5174"] = "PvP Flag"
    L["SOUND_NAME_878"] = "Interface Click"
    L["SOUND_NAME_569"] = "Menu Pop"
    L["SOUND_NAME_1080"] = "Rare Item"
    L["SOUND_NAME_8835"] = "Human Interface"
    L["SOUND_NAME_11742"] = "Epic Loot"
    L["SOUND_NAME_8477"] = "Ready Check"
    L["SOUND_NAME_3400"] = "Tower Alarm"
    L["SOUND_NAME_21388"] = "Whistle"
    
    L["DISPLAY_TIME"] = "Display Time"
    L["DISPLAY_TIME_DESC"] = "How many seconds notification stays visible on screen"
    L["SHOW_PORTRAIT"] = "Show Portrait"
    L["SHOW_PORTRAIT_DESC"] = "Display character portrait (only for players in group/nearby)"
    
    L["BTN_MOVE"] = "Move Anchor"
    L["BTN_MOVE_DESC"] = "Shows animated green anchor you can drag to reposition notifications"
    L["BTN_TEST"] = "Show Test"
    L["BTN_TEST_DESC"] = "Displays test notification to see how it's configured"
    L["BTN_RESET_POS"] = "Reset Position"
    L["BTN_RESET_POS_DESC"] = "Returns anchor to screen center (default position)"
    L["BTN_RESET_ALL"] = "Reset All"
    L["BTN_RESET_ALL_DESC"] = "Restores ALL settings to default values and reloads interface"
    L["BTN_RESET_CONFIRM"] = "Reset ALL settings?"
    
    L["ANCHOR_TEXT"] = "|cff00ff00Drag to Move|r\n|cffaaaaaa/wt move to hide|r"
    L["POS_SAVED"] = "|cff00ff00Position saved:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "Position reset"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "This is a test message to see how your customization looks!"

-- ========================================
-- ESPANHOL (esES/esMX)
-- ========================================
elseif locale == "esES" or locale == "esMX" then
    L["WHISPER_TITLE"] = "%s (Susurro):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (Hermandad):"
    L["PARTY_TITLE"] = "%s (Grupo):"
    L["RAID_TITLE"] = "%s (Banda):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "Configuración de WhisperToast.\n|cffff8800Comandos:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "Tipos de Notificaciones"
    L["SECTION_APPEARANCE"] = "Apariencia"
    L["SECTION_COLORS"] = "Colores"
    L["SECTION_SOUND"] = "Sonido"
    L["SECTION_BEHAVIOR"] = "Comportamiento"
    L["SECTION_POSITION"] = "Posicionamiento"
    
    L["WHISPER_TOGGLE"] = "Susurros y BNet"
    L["WHISPER_DESC"] = "Mostrar notificaciones de susurros"
    L["GUILD_TOGGLE"] = "Hermandad"
    L["GUILD_DESC"] = "Mostrar notificaciones de hermandad"
    L["PARTY_TOGGLE"] = "Grupo"
    L["PARTY_DESC"] = "Mostrar notificaciones de grupo"
    L["RAID_TOGGLE"] = "Banda"
    L["RAID_DESC"] = "Mostrar notificaciones de banda"
    
    L["WIDTH"] = "Anchura"
    L["HEIGHT"] = "Altura"
    L["MAX_CHARS"] = "Máx. Caracteres"
    L["MAX_CHARS_DESC"] = "Número máximo de caracteres mostrados"
    
    L["BG_COLOR"] = "Color de Fondo"
    L["BORDER_COLOR"] = "Color del Borde"
    L["TITLE_COLOR"] = "Color del Título"
    L["TEXT_COLOR"] = "Color del Texto"
    
    L["SOUND_ENABLE"] = "Activar Sonidos"
    L["SOUND_VOLUME"] = "Canal de Volumen"
    L["SOUND_WHISPER"] = "Sonido de Susurro"
    L["SOUND_GUILD"] = "Sonido de Hermandad"
    L["SOUND_PARTY"] = "Sonido de Grupo"
    L["SOUND_RAID"] = "Sonido de Banda"
    
    L["DISPLAY_TIME"] = "Tiempo de Visualización"
    L["SHOW_PORTRAIT"] = "Mostrar Retrato"
    L["SHOW_PORTRAIT_DESC"] = "Mostrar retrato del personaje"
    
    L["BTN_MOVE"] = "Mover Ancla"
    L["BTN_TEST"] = "Mostrar Prueba"
    L["BTN_RESET_POS"] = "Restablecer Posición"
    L["BTN_RESET_ALL"] = "Restablecer Todo"
    L["BTN_RESET_CONFIRM"] = "¿Restablecer TODAS las configuraciones?"
    
    L["ANCHOR_TEXT"] = "|cff00ff00Arrastra para Mover|r\n|cffaaaaaa/wt move para ocultar|r"
    L["POS_SAVED"] = "|cff00ff00Posición guardada:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "Posición restablecida"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "¡Este es un mensaje de prueba para ver cómo queda tu personalización!"

-- ========================================
-- FRANCÊS (frFR)
-- ========================================
elseif locale == "frFR" then
    L["WHISPER_TITLE"] = "%s (Chuchotement):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (Guilde):"
    L["PARTY_TITLE"] = "%s (Groupe):"
    L["RAID_TITLE"] = "%s (Raid):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "Paramètres de WhisperToast.\n|cffff8800Commandes:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "Types de Notifications"
    L["SECTION_APPEARANCE"] = "Apparence"
    L["SECTION_COLORS"] = "Couleurs"
    L["SECTION_SOUND"] = "Son"
    L["SECTION_BEHAVIOR"] = "Comportement"
    L["SECTION_POSITION"] = "Positionnement"
    
    L["WHISPER_TOGGLE"] = "Chuchotements et BNet"
    L["WHISPER_DESC"] = "Afficher les notifications de chuchotement"
    L["GUILD_TOGGLE"] = "Guilde"
    L["GUILD_DESC"] = "Afficher les notifications de guilde"
    L["PARTY_TOGGLE"] = "Groupe"
    L["PARTY_DESC"] = "Afficher les notifications de groupe"
    L["RAID_TOGGLE"] = "Raid"
    L["RAID_DESC"] = "Afficher les notifications de raid"
    
    L["WIDTH"] = "Largeur"
    L["HEIGHT"] = "Hauteur"
    L["MAX_CHARS"] = "Max. Caractères"
    L["MAX_CHARS_DESC"] = "Nombre maximum de caractères affichés"
    
    L["BG_COLOR"] = "Couleur de Fond"
    L["BORDER_COLOR"] = "Couleur de Bordure"
    L["TITLE_COLOR"] = "Couleur du Titre"
    L["TEXT_COLOR"] = "Couleur du Texte"
    
    L["SOUND_ENABLE"] = "Activer les Sons"
    L["SOUND_VOLUME"] = "Canal de Volume"
    L["SOUND_WHISPER"] = "Son de Chuchotement"
    L["SOUND_GUILD"] = "Son de Guilde"
    L["SOUND_PARTY"] = "Son de Groupe"
    L["SOUND_RAID"] = "Son de Raid"
    
    L["DISPLAY_TIME"] = "Temps d'Affichage"
    L["SHOW_PORTRAIT"] = "Afficher le Portrait"
    L["SHOW_PORTRAIT_DESC"] = "Afficher le portrait du personnage"
    
    L["BTN_MOVE"] = "Déplacer l'Ancre"
    L["BTN_TEST"] = "Afficher un Test"
    L["BTN_RESET_POS"] = "Réinitialiser la Position"
    L["BTN_RESET_ALL"] = "Tout Réinitialiser"
    L["BTN_RESET_CONFIRM"] = "Réinitialiser TOUS les paramètres?"
    
    L["ANCHOR_TEXT"] = "|cff00ff00Glisser pour Déplacer|r\n|cffaaaaaa/wt move pour cacher|r"
    L["POS_SAVED"] = "|cff00ff00Position sauvegardée:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "Position réinitialisée"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "Ceci est un message de test pour voir votre personnalisation!"

-- ========================================
-- ALEMÃO (deDE)
-- ========================================
elseif locale == "deDE" then
    L["WHISPER_TITLE"] = "%s (Flüstern):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (Gilde):"
    L["PARTY_TITLE"] = "%s (Gruppe):"
    L["RAID_TITLE"] = "%s (Schlachtzug):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "WhisperToast Einstellungen.\n|cffff8800Befehle:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "Benachrichtigungstypen"
    L["SECTION_APPEARANCE"] = "Aussehen"
    L["SECTION_COLORS"] = "Farben"
    L["SECTION_SOUND"] = "Ton"
    L["SECTION_BEHAVIOR"] = "Verhalten"
    L["SECTION_POSITION"] = "Positionierung"
    
    L["WHISPER_TOGGLE"] = "Flüstern & BNet"
    L["WHISPER_DESC"] = "Flüsterbenachrichtigungen anzeigen"
    L["GUILD_TOGGLE"] = "Gilde"
    L["GUILD_DESC"] = "Gildenbenachrichtigungen anzeigen"
    L["PARTY_TOGGLE"] = "Gruppe"
    L["PARTY_DESC"] = "Gruppenbenachrichtigungen anzeigen"
    L["RAID_TOGGLE"] = "Schlachtzug"
    L["RAID_DESC"] = "Schlachtzugbenachrichtigungen anzeigen"
    
    L["WIDTH"] = "Breite"
    L["HEIGHT"] = "Höhe"
    L["MAX_CHARS"] = "Max. Zeichen"
    L["MAX_CHARS_DESC"] = "Maximale Anzahl angezeigter Zeichen"
    
    L["BG_COLOR"] = "Hintergrundfarbe"
    L["BORDER_COLOR"] = "Rahmenfarbe"
    L["TITLE_COLOR"] = "Titelfarbe"
    L["TEXT_COLOR"] = "Textfarbe"
    
    L["SOUND_ENABLE"] = "Töne Aktivieren"
    L["SOUND_VOLUME"] = "Lautstärkekanal"
    L["SOUND_WHISPER"] = "Flüsterton"
    L["SOUND_GUILD"] = "Gildenton"
    L["SOUND_PARTY"] = "Gruppenton"
    L["SOUND_RAID"] = "Schlachtzugton"
    
    L["DISPLAY_TIME"] = "Anzeigezeit"
    L["SHOW_PORTRAIT"] = "Porträt Anzeigen"
    L["SHOW_PORTRAIT_DESC"] = "Charakterporträt anzeigen"
    
    L["BTN_MOVE"] = "Anker Bewegen"
    L["BTN_TEST"] = "Test Anzeigen"
    L["BTN_RESET_POS"] = "Position Zurücksetzen"
    L["BTN_RESET_ALL"] = "Alles Zurücksetzen"
    L["BTN_RESET_CONFIRM"] = "ALLE Einstellungen zurücksetzen?"
    
    L["ANCHOR_TEXT"] = "|cff00ff00Ziehen zum Bewegen|r\n|cffaaaaaa/wt move zum Verstecken|r"
    L["POS_SAVED"] = "|cff00ff00Position gespeichert:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "Position zurückgesetzt"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "Dies ist eine Testnachricht, um Ihre Anpassung zu sehen!"

-- ========================================
-- RUSSO (ruRU)
-- ========================================
elseif locale == "ruRU" then
    L["WHISPER_TITLE"] = "%s (Whisper):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (Guild):"
    L["PARTY_TITLE"] = "%s (Party):"
    L["RAID_TITLE"] = "%s (Raid):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "WhisperToast Einstellungen.\n|cffff8800Befehle:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "Notification Types"
    L["SECTION_APPEARANCE"] = "Appearance"
    L["SECTION_COLORS"] = "Colors"
    L["SECTION_SOUND"] = "Sound"
    L["SECTION_BEHAVIOR"] = "Behavior"
    L["SECTION_POSITION"] = "Positioning"
    
    L["WHISPER_TOGGLE"] = "Whispers & BNet"
    L["WHISPER_DESC"] = "Show whisper notifications"
    L["GUILD_TOGGLE"] = "Guild"
    L["GUILD_DESC"] = "Show guild notifications"
    L["PARTY_TOGGLE"] = "Party"
    L["PARTY_DESC"] = "Show party notifications"
    L["RAID_TOGGLE"] = "Raid"
    L["RAID_DESC"] = "Show raid notifications"
    
    L["WIDTH"] = "Width"
    L["HEIGHT"] = "Height"
    L["MAX_CHARS"] = "Max Characters"
    L["MAX_CHARS_DESC"] = "Maximum characters displayed"
    
    L["BG_COLOR"] = "Background Color"
    L["BORDER_COLOR"] = "Border Color"
    L["TITLE_COLOR"] = "Title Color"
    L["TEXT_COLOR"] = "Text Color"
    
    L["SOUND_ENABLE"] = "Enable Sounds"
    L["SOUND_VOLUME"] = "Volume Channel"
    L["SOUND_VOLUME_MASTER"] = "Master"
    L["SOUND_VOLUME_SOUND"] = "Sound Effects"
    L["SOUND_VOLUME_MUSIC"] = "Music"
    L["SOUND_VOLUME_AMBIENCE"] = "Ambience"
    L["SOUND_VOLUME_DIALOG"] = "Dialog"
    L["SOUND_WHISPER"] = "Whisper Sound"
    L["SOUND_GUILD"] = "Guild Sound"
    L["SOUND_PARTY"] = "Party Sound"
    L["SOUND_RAID"] = "Raid Sound"
    
    L["DISPLAY_TIME"] = "Display Time"
    L["SHOW_PORTRAIT"] = "Show Portrait"
    L["SHOW_PORTRAIT_DESC"] = "Display character portrait"
    
    L["BTN_MOVE"] = "Move Anchor"
    L["BTN_TEST"] = "Show Test"
    L["BTN_RESET_POS"] = "Reset Position"
    L["BTN_RESET_ALL"] = "Reset All"
    L["BTN_RESET_CONFIRM"] = "Reset ALL settings?"
    
    L["ANCHOR_TEXT"] = "|cff00ff00Drag to Move|r|cffaaaaaa/wt move to hide|r"
    L["POS_SAVED"] = "|cff00ff00Position saved:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "Position reset"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "This is a test message to see how your customization looks!"
    
    -- Sound Names
    L["SOUND_NAME_11504"] = "Whisper (Default)"
    L["SOUND_NAME_8960"] = "Guild (Default)"
    L["SOUND_NAME_11487"] = "Party (Default)"
    L["SOUND_NAME_567"] = "Map Open"
    L["SOUND_NAME_850"] = "Bell"
    L["SOUND_NAME_1190"] = "Chest Looted"
    L["SOUND_NAME_5274"] = "Gong"
    L["SOUND_NAME_8959"] = "Tell"
    L["SOUND_NAME_12867"] = "Door Opening"
    L["SOUND_NAME_29495"] = "Fanfare"
    L["SOUND_NAME_3081"] = "Money Looted"
    L["SOUND_NAME_5841"] = "Level Up"
    L["SOUND_NAME_12889"] = "Raid Warning"
    L["SOUND_NAME_8745"] = "Achievement"
    L["SOUND_NAME_11466"] = "Quest Complete"
    L["SOUND_NAME_6595"] = "Exploration"
    L["SOUND_NAME_5174"] = "PvP Flag"
    L["SOUND_NAME_878"] = "Interface Click"
    L["SOUND_NAME_569"] = "Menu Pop"
    L["SOUND_NAME_1080"] = "Rare Item"
    L["SOUND_NAME_8835"] = "Human Interface"
    L["SOUND_NAME_11742"] = "Epic Loot"
    L["SOUND_NAME_8477"] = "Ready Check"
    L["SOUND_NAME_3400"] = "Tower Alarm"
    L["SOUND_NAME_21388"] = "Whistle"

elseif locale == "koKR" then
    L["WHISPER_TITLE"] = "%s (귓속말):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (길드):"
    L["PARTY_TITLE"] = "%s (파티):"
    L["RAID_TITLE"] = "%s (공격대):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "WhisperToast 설정.\n|cffff8800�령어:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "알림 유형"
    L["SECTION_APPEARANCE"] = "외형"
    L["SECTION_COLORS"] = "색상"
    L["SECTION_SOUND"] = "사운드"
    L["SECTION_BEHAVIOR"] = "동작"
    L["SECTION_POSITION"] = "위치"
    
    L["WHISPER_TOGGLE"] = "귓속말 & BNet"
    L["WHISPER_DESC"] = "귓속말 알림 표시"
    L["GUILD_TOGGLE"] = "길드"
    L["GUILD_DESC"] = "길드 알림 표시"
    L["PARTY_TOGGLE"] = "파티"
    L["PARTY_DESC"] = "파티 알림 표시"
    L["RAID_TOGGLE"] = "공격대"
    L["RAID_DESC"] = "공격대 알림 표시"
    
    L["WIDTH"] = "너비"
    L["HEIGHT"] = "높이"
    L["MAX_CHARS"] = "최대 문자"
    L["MAX_CHARS_DESC"] = "표시되는 최대 문자 수"
    
    L["BG_COLOR"] = "배경 색상"
    L["BORDER_COLOR"] = "��두리 색상"
    L["TITLE_COLOR"] = "제목 색상"
    L["TEXT_COLOR"] = "��스트 색상"
    
    L["SOUND_ENABLE"] = "사운드 활성화"
    L["SOUND_VOLUME"] = "볼륨 채널"
    L["SOUND_WHISPER"] = "귓속말 사운드"
    L["SOUND_GUILD"] = "길드 사운드"
    L["SOUND_PARTY"] = "파티 사운드"
    L["SOUND_RAID"] = "공격대 사운드"
    
    L["DISPLAY_TIME"] = "표시 시간"
    L["SHOW_PORTRAIT"] = "초상화 표시"
    L["SHOW_PORTRAIT_DESC"] = "캐릭터 초상화 표시"
    
    L["BTN_MOVE"] = "고정 위치 이동"
    L["BTN_TEST"] = "��스트 표시"
    L["BTN_RESET_POS"] = "위치 초기화"
    L["BTN_RESET_ALL"] = "모두 초기화"
    L["BTN_RESET_CONFIRM"] = "모든 설정을 초기화하시겠습니까?"
    
    L["ANCHOR_TEXT"] = "|cff00ff00드래그하여 이동|r\n|cffaaaaaa/wt move 숨기기|r"
    L["POS_SAVED"] = "|cff00ff00위치 저장됨:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "위치 초기화됨"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "사용자 정의를 보기 위한 ��스트 메시지�니다!"

-- ========================================
-- CHINÊS SIMPLIFICADO (zhCN)
-- ========================================
elseif locale == "zhCN" then
    L["WHISPER_TITLE"] = "%s (密语):"
    L["BNET_TITLE"] = "%s (战网):"
    L["GUILD_TITLE"] = "%s (��会):"
    L["PARTY_TITLE"] = "%s (小队):"
    L["RAID_TITLE"] = "%s (团队):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "WhisperToast 设置.\n|cffff8800命令:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "通知类型"
    L["SECTION_APPEARANCE"] = "外观"
    L["SECTION_COLORS"] = "颜色"
    L["SECTION_SOUND"] = "声音"
    L["SECTION_BEHAVIOR"] = "行为"
    L["SECTION_POSITION"] = "定位"
    
    L["WHISPER_TOGGLE"] = "密语 & 战网"
    L["WHISPER_DESC"] = "显示密语通知"
    L["GUILD_TOGGLE"] = "��会"
    L["GUILD_DESC"] = "显示��会通知"
    L["PARTY_TOGGLE"] = "小队"
    L["PARTY_DESC"] = "显示小队通知"
    L["RAID_TOGGLE"] = "团队"
    L["RAID_DESC"] = "显示团队通知"
    
    L["WIDTH"] = "宽度"
    L["HEIGHT"] = "高度"
    L["MAX_CHARS"] = "最大字符"
    L["MAX_CHARS_DESC"] = "显示的最大字符数"
    
    L["BG_COLOR"] = "背景颜色"
    L["BORDER_COLOR"] = "边框颜色"
    L["TITLE_COLOR"] = "标题颜色"
    L["TEXT_COLOR"] = "文本颜色"
    
    L["SOUND_ENABLE"] = "启用声音"
    L["SOUND_VOLUME"] = "音量频道"
    L["SOUND_WHISPER"] = "密语声音"
    L["SOUND_GUILD"] = "��会声音"
    L["SOUND_PARTY"] = "小队声音"
    L["SOUND_RAID"] = "团队声音"
    
    L["DISPLAY_TIME"] = "显示时间"
    L["SHOW_PORTRAIT"] = "显示肖像"
    L["SHOW_PORTRAIT_DESC"] = "显示角色肖像"
    
    L["BTN_MOVE"] = "移动锚点"
    L["BTN_TEST"] = "显示测试"
    L["BTN_RESET_POS"] = "重置位置"
    L["BTN_RESET_ALL"] = "��部重置"
    L["BTN_RESET_CONFIRM"] = "重置所有设置？"
    
    L["ANCHOR_TEXT"] = "|cff00ff00拖动移动|r\n|cffaaaaaa/wt move 隐藏|r"
    L["POS_SAVED"] = "|cff00ff00位置已保存:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "位置已重置"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "这是一条测试消息，看看你的自定义效果！"

-- ========================================
-- CHINÊS TRADICIONAL (zhTW)
-- ========================================
elseif locale == "zhTW" then
    L["WHISPER_TITLE"] = "%s (密語):"
    L["BNET_TITLE"] = "%s (戰網):"
    L["GUILD_TITLE"] = "%s (��會):"
    L["PARTY_TITLE"] = "%s (隊伍):"
    L["RAID_TITLE"] = "%s (團隊):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "WhisperToast 設定.\n|cffff8800指令:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "通知類型"
    L["SECTION_APPEARANCE"] = "外觀"
    L["SECTION_COLORS"] = "顏色"
    L["SECTION_SOUND"] = "聲音"
    L["SECTION_BEHAVIOR"] = "行為"
    L["SECTION_POSITION"] = "定位"
    
    L["WHISPER_TOGGLE"] = "密語 & 戰網"
    L["WHISPER_DESC"] = "顯示密語通知"
    L["GUILD_TOGGLE"] = "��會"
    L["GUILD_DESC"] = "顯示��會通知"
    L["PARTY_TOGGLE"] = "隊伍"
    L["PARTY_DESC"] = "顯示隊伍通知"
    L["RAID_TOGGLE"] = "團隊"
    L["RAID_DESC"] = "顯示團隊通知"
    
    L["WIDTH"] = "寬度"
    L["HEIGHT"] = "高度"
    L["MAX_CHARS"] = "最大字��"
    L["MAX_CHARS_DESC"] = "顯示的最大字��數"
    
    L["BG_COLOR"] = "背景顏色"
    L["BORDER_COLOR"] = "邊框顏色"
    L["TITLE_COLOR"] = "標題顏色"
    L["TEXT_COLOR"] = "文字顏色"
    
    L["SOUND_ENABLE"] = "啟用聲音"
    L["SOUND_VOLUME"] = "音量頻道"
    L["SOUND_WHISPER"] = "密語聲音"
    L["SOUND_GUILD"] = "��會聲音"
    L["SOUND_PARTY"] = "隊伍聲音"
    L["SOUND_RAID"] = "團隊聲音"
    
    L["DISPLAY_TIME"] = "顯示時間"
    L["SHOW_PORTRAIT"] = "顯示肖像"
    L["SHOW_PORTRAIT_DESC"] = "顯示角色肖像"
    
    L["BTN_MOVE"] = "移動錨點"
    L["BTN_TEST"] = "顯示測試"
    L["BTN_RESET_POS"] = "重置位置"
    L["BTN_RESET_ALL"] = "��部重置"
    L["BTN_RESET_CONFIRM"] = "重置所有設定？"
    
    L["ANCHOR_TEXT"] = "|cff00ff00拖曳移動|r\n|cffaaaaaa/wt move 隱藏|r"
    L["POS_SAVED"] = "|cff00ff00位置已儲存:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "位置已重置"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "這是一則測試訊息，看看你的自訂效果！"

-- ========================================
-- PADRÃO (fallback para inglês)
-- ========================================
else
    -- Usar inglês como padrão
    L["WHISPER_TITLE"] = "%s (Whisper):"
    L["BNET_TITLE"] = "%s (BNet):"
    L["GUILD_TITLE"] = "%s (Guild):"
    L["PARTY_TITLE"] = "%s (Party):"
    L["RAID_TITLE"] = "%s (Raid):"
    
    L["OPTIONS_TITLE"] = "WhisperToast"
    L["OPTIONS_DESC"] = "WhisperToast Settings.\n|cffff8800Commands:|r /wt move | /wt test"
    
    L["SECTION_NOTIFICATIONS"] = "Notification Types"
    L["SECTION_APPEARANCE"] = "Appearance"
    L["SECTION_COLORS"] = "Colors"
    L["SECTION_SOUND"] = "Sound"
    L["SECTION_BEHAVIOR"] = "Behavior"
    L["SECTION_POSITION"] = "Positioning"
    
    L["WHISPER_TOGGLE"] = "Whispers & BNet"
    L["WHISPER_DESC"] = "Show whisper notifications"
    L["GUILD_TOGGLE"] = "Guild"
    L["GUILD_DESC"] = "Show guild notifications"
    L["PARTY_TOGGLE"] = "Party"
    L["PARTY_DESC"] = "Show party notifications"
    L["RAID_TOGGLE"] = "Raid"
    L["RAID_DESC"] = "Show raid notifications"
    
    L["WIDTH"] = "Width"
    L["HEIGHT"] = "Height"
    L["MAX_CHARS"] = "Max Characters"
    L["MAX_CHARS_DESC"] = "Maximum characters displayed"
    
    L["BG_COLOR"] = "Background Color"
    L["BORDER_COLOR"] = "Border Color"
    L["TITLE_COLOR"] = "Title Color"
    L["TEXT_COLOR"] = "Text Color"
    
    L["SOUND_ENABLE"] = "Enable Sounds"
    L["SOUND_VOLUME"] = "Volume Channel"
    L["SOUND_VOLUME_MASTER"] = "Master"
    L["SOUND_VOLUME_SOUND"] = "Sound Effects"
    L["SOUND_VOLUME_MUSIC"] = "Music"
    L["SOUND_VOLUME_AMBIENCE"] = "Ambience"
    L["SOUND_VOLUME_DIALOG"] = "Dialog"
    L["SOUND_WHISPER"] = "Whisper Sound"
    L["SOUND_GUILD"] = "Guild Sound"
    L["SOUND_PARTY"] = "Party Sound"
    L["SOUND_RAID"] = "Raid Sound"
    -- Sound Names
    L["SOUND_NAME_11504"] = "Whisper (Default)"
    L["SOUND_NAME_8960"] = "Guild (Default)"
    L["SOUND_NAME_11487"] = "Party (Default)"
    L["SOUND_NAME_567"] = "Map Open"
    L["SOUND_NAME_850"] = "Bell"
    L["SOUND_NAME_1190"] = "Chest Looted"
    L["SOUND_NAME_5274"] = "Gong"
    L["SOUND_NAME_8959"] = "Tell"
    L["SOUND_NAME_12867"] = "Door Opening"
    L["SOUND_NAME_29495"] = "Fanfare"
    L["SOUND_NAME_3081"] = "Money Looted"
    L["SOUND_NAME_5841"] = "Level Up"
    L["SOUND_NAME_12889"] = "Raid Warning"
    L["SOUND_NAME_8745"] = "Achievement"
    L["SOUND_NAME_11466"] = "Quest Complete"
    L["SOUND_NAME_6595"] = "Exploration"
    L["SOUND_NAME_5174"] = "PvP Flag"
    L["SOUND_NAME_878"] = "Interface Click"
    L["SOUND_NAME_569"] = "Menu Pop"
    L["SOUND_NAME_1080"] = "Rare Item"
    L["SOUND_NAME_8835"] = "Human Interface"
    L["SOUND_NAME_11742"] = "Epic Loot"
    L["SOUND_NAME_8477"] = "Ready Check"
    L["SOUND_NAME_3400"] = "Tower Alarm"
    L["SOUND_NAME_21388"] = "Whistle"
    
    L["DISPLAY_TIME"] = "Display Time"
    L["SHOW_PORTRAIT"] = "Show Portrait"
    L["SHOW_PORTRAIT_DESC"] = "Display character portrait"
    
    L["BTN_MOVE"] = "Move Anchor"
    L["BTN_TEST"] = "Show Test"
    L["BTN_RESET_POS"] = "Reset Position"
    L["BTN_RESET_ALL"] = "Reset All"
    L["BTN_RESET_CONFIRM"] = "Reset ALL settings?"
    
    L["ANCHOR_TEXT"] = "|cff00ff00Drag to Move|r\n|cffaaaaaa/wt move to hide|r"
    L["POS_SAVED"] = "|cff00ff00Position saved:|r %s (X: %d, Y: %d)"
    L["POS_RESET"] = "Position reset"
    L["SLASH_HELP"] = "Use the addon options via: ESC > Interface > AddOns > WhisperToast"
    L["TEST_MESSAGE"] = "This is a test message to see how your customization looks!"
end

-- Exportar tabela de localização
WhisperToast_Locale = L

