name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build addon with BigWigs packager
        run: |
          curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s -- -l

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whispertoast-release
          path: .release/*

      - name: Publish to CurseForge
        if: ${{ secrets.CURSEFORGE_API_TOKEN != '' && secrets.CURSEFORGE_GAME_VERSION_IDS != '' }}
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_API_TOKEN }}
          GAME_VERSION_IDS: ${{ secrets.CURSEFORGE_GAME_VERSION_IDS }}
          PROJECT_ID: "1367932"
        shell: bash
        run: |
          ZIP_PATH=$(ls .release/*.zip | head -n 1)
          if [ -z "$ZIP_PATH" ]; then
            echo "No release zip found in .release/"
            exit 1
          fi

          VERSION="${GITHUB_REF#refs/tags/}"
          if [ "$VERSION" = "$GITHUB_REF" ] || [ -z "$VERSION" ]; then
            VERSION="${GITHUB_SHA::7}"
          fi

          export VERSION
          python - <<'PY'
    import json, os

    version = os.environ["VERSION"]
    game_versions = [
        int(item.strip())
        for item in os.environ["GAME_VERSION_IDS"].split(",")
        if item.strip()
    ]

    metadata = {
        "displayName": f"WhisperToast {version}",
        "gameVersions": game_versions,
        "releaseType": "release",
        "changelogType": "markdown",
        "changelog": f"Automated build {version}",
    }

    with open("metadata.json", "w", encoding="utf-8") as fp:
        json.dump(metadata, fp)
          PY

          curl -sS -X POST \
            -H "x-api-token: ${CURSEFORGE_TOKEN}" \
            -F "metadata=@metadata.json" \
            -F "file=@${ZIP_PATH}" \
            "https://www.curseforge.com/api/projects/${PROJECT_ID}/package"
