name: Release to CurseForge
on:
  push:
    tags:
      - 'v*'                # dispara quando um tag inicia com v

jobs:
  curseforge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Zip addon
        run: |
          Compress-Archive -Path WhisperToast -DestinationPath WhisperToast-${{ github.ref_name }}.zip -Force

      - name: Upload to CurseForge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        run: |
          $projectId = 1367932
          $file = "WhisperToast-${{ github.ref_name }}.zip"
          $changelog = Get-Content CHANGELOG.md -Raw  # ou defina inline
          $metadata = @{
            changelog     = $changelog
            changelogType = "markdown"
            displayName   = "${{ github.ref_name }}"
            gameVersions  = @("10.2.5")
            releaseType   = "release"
          }
          # mesmo bloco PowerShell de multipart usado acima...
