name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build addon with BigWigs packager
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWINTERFACE_API_TOKEN: ${{ secrets.WOWINTERFACE_API_TOKEN }}
        run: |
          curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash -s --

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: whispertoast-release
          path: .release/*
